project:
  type: website

website:
  title: "Notes from a Data Witch"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/djnavarro
      - icon: twitter
        href: https://twitter.com/djnavarro
format:
  html:
    theme: litera
    css: styles.css



